---
- hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: instance
      prompt: "What is Instanece-ID?"
      confirm: yes
      private: no  
  tasks:
    - name: Terminate the instance
      ec2:
        state: 'absent'
        instance_ids: "{{instance}}"
        region: "{{region}}"
        
  